all:
  hosts:
    moode01:
      moode:                        one
      ansible_connection:           ssh
      ansible_user:                 pi
      ansible_host:                 moode01.toffee.ro
      ansible_ssh_private_key_file: ~/git/smartserver/config/jupiter/vault/ssh_auth/auth-moode01.toffee.ro
      host_name:                    "moode-one"
      macaddress:                   "e4:5f:01:10:4f:44"
      
    moode02:
      moode:                        two
      ansible_connection:           ssh
      ansible_user:                 pi
      ansible_host:                 moode02.toffee.ro
      ansible_ssh_private_key_file: ~/git/smartserver/config/jupiter/vault/ssh_auth/auth-moode02.toffee.ro
      host_name:                    "moode-two"
      macaddress:                   "e4:5f:01:4d:ab:d4" 

