all:
  hosts:
    snapserver:
      ansible_connection:           ssh
      ansible_user:                 pi
      ansible_host:                 192.168.120.71
      ansible_ssh_private_key_file: ~/git/toffee/smartserver/config/jupiter/vault/ssh_auth/snapserver.toffee.ro
      host_name:                    "snapserver"
      isserver:                     true
      alsa_card:                    "0"
      alsa_mixer:                   "Digital"
      hifiberry:                    "amp"
      snapserver_host:              "127.0.0.1"
      snapclient_left_opts:         "--host {{snapserver_host}} --port {{snapserver_port}} --hostID one-left --soundcard left --player alsa --sampleformat 48000:16:* --mixer script:/usr/local/bin/volume-left.sh"
      snapclient_right_opts:        "--host {{snapserver_host}} --port {{snapserver_port}} --hostID one-right --soundcard right --player alsa --sampleformat 48000:16:* --mixer script:/usr/local/bin/volume-right.sh"

    universum:
      ansible_connection:           ssh
      ansible_user:                 daniel
      ansible_host:                 192.168.120.73
      ansible_ssh_private_key_file: ~/git/toffee/smartserver/config/jupiter/vault/ssh_auth/universum-private-key-20241217.openssh
      host_name:                    "universum"
      isserver:                     "false"
      alsa_card:                    "0"
      alsa_mixer:                   "Master"
      hifiberry:                    "miniamp"
      snapclient_stereo_opts:       "--host {{snapserver_host}} --port {{snapserver_port}} --hostID universum --soundcard stereo --player alsa --sampleformat 48000:16:* --mixer script:/usr/local/bin/volume-stereo.sh"

  vars:
    snapserver_host:                "192.168.120.71"
    snapserver_port:                "1704"