- hosts: all
  become: true

  pre_tasks:
    # load shared variables
    - name: load shared vars
      include_vars: "config/shared.yml"
      tags: always 
  
    - name: loaded values from config files
      debug:
        msg: 
          - "snapserver host:       {{snapserver_host}}"
          - "snapserver port:       {{snapserver_port}}"
          - "alsa mixer:            {{alsa_mixer}}"
          - "snapclient left opt:   {{snapclient_left_opts}}"
          - "snapclient right opt:  {{snapclient_right_opts}}"
      tags: always 

  roles:
    - alsa
    - snapserver
    - snapclient
    - mpd
