- hosts: all
  become: true

  pre_tasks:
    # load shared variables
    - name: load shared vars
      include_vars: "config/shared.yml"
      tags: always 
      
    - name: define variable moode
      set_fact:
        moode: "{{ (ansible_facts['eth0'].macaddress == macaddress_one) | ternary ('one', 'two') }}"
        
    - name: load specific vars
      include_vars: "config/{{moode}}.yml"
      tags: always 
  
    - name: loaded values from config files
      debug:
        msg: 
          - "mac address:           {{ansible_facts['eth0'].macaddress}}"
          - "moode:                 {{moode}}"
          - "snapserver host:       {{snapserver_host}}"
          - "snapserver port:       {{snapserver_port}}"
          - "alsa mixer:            {{alsa_mixer}}"
          - "snapclient left opt:   {{snapclient_left_opts}}"
          - "snapclient right opt:  {{snapclient_right_opts}}"
      tags: always 
      
    - name: set hostname
      shell: 'hostnamectl set-hostname {{host_name}}'
      changed_when: "ansible_hostname != host_name"

  roles:
    - role: alsa
    - role: snapserver
      when: moode == 'one'
    - role: snapclient
    - role: mpd
      when: moode == 'one'
    - role: mympd
      when: moode == 'one'
