- hosts: all
  become: true

  pre_tasks:
    # load vault file
    - name: load vault vars
      include_vars: "config/vault/vault.yml"
      tags: always 
      
    - name: loaded values from config files
      debug:
        msg: 
          - "host_name:             {{host_name}}"
      tags: always 

    - name: set hostname
      shell: 'hostnamectl set-hostname {{host_name}}'
      changed_when: "ansible_hostname != host_name"

    - name: Replace a localhost entry pointing to old hostname
      lineinfile:
        path: /etc/hosts
        regexp: 'moode'
        line: 127.0.0.1         {{host_name}}

    - name: install additional packages
      apt:
        name: [
          vim,
          mc
        ]
        state: present 
      tags: always 

  roles:
    - role: raspberrypi
      when: inventory_hostname == 'universum'
    - role: alsa
    - role: snapserver
      tags: snapserver
      when: isserver | bool
    - role: snapclient
      tags: snapclient
    - role: mpd
      tags: mpd
      when: isserver | bool
    - role: mympd
      tags: mympd
      when: isserver | bool
    - role: airplay
      tags: airplay
      when: isserver | bool
    - role: pulseaudio
      tags: pulseaudio
      when: isserver | bool