---
- name: install snapclient
  apt:
    deb: "https://github.com/badaix/snapcast/releases/download/v0.29.0/snapclient_0.29.0-1_arm64_bookworm.deb"

- name: disable original snapclient init.d
  lineinfile:
    path: "/etc/default/snapclient"
    regexp: "^START_SNAPCLIENT="
    line: "START_SNAPCLIENT=false"

- name: stop original snapclient if running
  systemd:
    name: snapclient
    state: stopped
    enabled: no

# this directory is owned by original user _snapclient (probbaly come from the raspberry package instalation)
- name: fix home directory permission for user snapclient
  ansible.builtin.file:
    path: /var/lib/snapclient
    owner: snapclient
    group: snapclient
    mode: '0700'

- name: configure instance left
  vars:
    instance: "left"
    config: "{{snapclient_left_opts}}"
  include_tasks: add_instance.yml
  when: snapclient_left_opts is defined

- name: configure instance right
  vars:
    instance: "right"
    config: "{{snapclient_right_opts}}"
  include_tasks: add_instance.yml
  when: snapclient_right_opts is defined
  
- name: configure instance stereo
  vars:
    instance: "stereo"
    config: "{{snapclient_stereo_opts}}"
  include_tasks: add_instance.yml
  when: snapclient_stereo_opts is defined