- name: copy alsa configuration
  template:
    src: "templates{{item}}"
    dest: "{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - "/etc/alsa/conf.d/_common.conf"
    - "/etc/alsa/conf.d/_left.conf"
    - "/etc/alsa/conf.d/_right.conf"
    - "/etc/alsa/conf.d/_mono.conf"
