macaddress_one:         "e4:5f:01:10:4f:44"
macaddress_two:         "e4:5f:01:4d:ab:d4"

snapserver_host:        "192.168.120.71"
snapserver_port:        "1704"

snapclient_left_opts:   "--host {{snapserver_host}} --port {{snapserver_port}} --hostID left{{moode}} --soundcard left --player alsa --mixer script:/usr/local/bin/volume-left.sh"
snapclient_right_opts:  "--host {{snapserver_host}} --port {{snapserver_port}} --hostID right{{moode}} --soundcard right --player alsa --mixer script:/usr/local/bin/volume-right.sh"

alsa_mixer:             "Digital"

