---
- name: "copy mpd service file"
  template:
    src: "templates/mpd-@.service"
    dest: "/lib/systemd/system/mpd-@.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mpd-@library
    - restart mpd-@radio

- name: force systemd to reread configs
  systemd:
    daemon_reload: yes    
    
- name: define variable library
  set_fact:
    side: "library"
    mpd_port: "6601"

- name: "copy mpd config '{{side}}'"
  template:
    src: "templates/mpd.conf"
    dest: "/etc/mpd-{{side}}.conf"
    owner: mpd
    group: audio
    mode: 0666
  notify:
    - restart mpd-@{{side}}
 
- name: Start service mpd-@{{side}}
  systemd:
    name: mpd-@{{side}}
    state: started
    enabled: yes  
 
- name: define variable radio
  set_fact:
    side: "radio"
    mpd_port: "6602"

- name: "copy mpd config '{{side}}'"
  template:
    src: "templates/mpd.conf"
    dest: "/etc/mpd-{{side}}.conf"
    owner: mpd
    group: audio
    mode: 0666
  notify:
    - restart mpd-@{{side}}

- name: Start service mpd-@{{side}}
  systemd:
    name: mpd-@{{side}}
    state: started
    enabled: yes  

- name: "copy playlist with radios from Romania"
  template:
    src: "templates/Radio-Romania.m3u"
    dest: "/var/lib/mpd/playlists"
    owner: mpd
    group: audio
    mode: 0666

