---
- name: install required packages
  apt:
    deb: https://download.opensuse.org/repositories/home:/jcorporation/Raspbian_11/armhf/mympd_18.2.2-1_armhf.deb

- name: "copy mympd service file"
  template:
    src: "templates/mympd-@.service"
    dest: "/lib/systemd/system/mympd-@.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mympd-@library
    - restart mympd-@radio
    
- name: force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: configure instance library
  vars:
    instance: "library"
    http_port: "6681"
    ssl_port: "6691"
    mpd_host: "127.0.0.1"
    mpd_port: "6601"
  include_tasks: add_instance.yml

- name: configure instance radio
  vars:
    instance: "radio"
    http_port: "6682"
    ssl_port: "6693"
    mpd_host: "127.0.0.1"
    mpd_port: "6602"
  include_tasks: add_instance.yml
