- name: install snapserver
  apt:
    deb: "https://github.com/badaix/snapcast/releases/download/v0.29.0/snapserver_0.29.0-1_arm64_bullseye.deb"

# for meta_mpd.py to work must install:
# pip install python-mpd2
- name: install python-mpd2
  pip:
    name: 
      - python-mpd2
      - musicbrainzngs

- name: define variable library
  set_fact:
    side: "library"
    mpd_port: "6601"

- name: "copy meta_mpd.sh '{{side}}'"
  template:
    src: "templates/meta_mpd.sh"
    dest: "/usr/share/snapserver/plug-ins/meta_mpd_{{side}}.sh"
    mode: 0755

- name: define variable radio
  set_fact:
    side: "radio"
    mpd_port: "6602"
    
- name: "copy meta_mpd.sh '{{side}}'"
  template:
    src: "templates/meta_mpd.sh"
    dest: "/usr/share/snapserver/plug-ins/meta_mpd_{{side}}.sh"
    mode: 0755

- name: modify snapserver sources
  lineinfile:
    path: "/etc/snapserver.conf"
    insertafter: "^# meta: meta:"
    line: "source = pipe:///tmp/snapfifolibrary?name=Source-Library&controlscript=meta_mpd_library.sh"
  notify: restart snapserver
  
- name: modify snapserver sources
  lineinfile:
    path: "/etc/snapserver.conf"
    insertafter: "^# meta: meta:"
    line: "source = pipe:///tmp/snapfiforadio?name=Source-Radio&controlscript=meta_mpd_radio.sh"
  notify: restart snapserver

- name: modify snapserver sources
  lineinfile:
    path: "/etc/snapserver.conf"
    insertafter: "^# meta: meta:"
    line: "source = pipe:///tmp/snapfifoairplay?name=Source-Airplay&sampleformat=44100:16:2"
  notify: restart snapserver 

- name: modify snapserver sources
  lineinfile:
    path: "/etc/snapserver.conf"
    insertafter: "^# meta: meta:"
    line: "source = spotify:///librespot?name=Source-Spotify&username={{vault_spotify_username}}&password={{vault_spotify_password}}&devicename=Snapcast&bitrate=320&disable_audio_cache=true&killall=true"
  notify: restart snapserver

- name: modify snapserver sources
  lineinfile:
    path: "/etc/snapserver.conf"
    insertafter: "^# meta: meta:"
    line: "source = pipe:///tmp/snapfifopulseaudio?name=Source-Pulse"
  notify: restart snapserver

- name: remove default source
  lineinfile:
    path: "/etc/snapserver.conf"
    regexp: "source = pipe:///tmp/snapfifo\\?name=default"
    state: absent
  notify: restart snapserver 
