- name: install snapserver
  apt:
    deb: "https://github.com/badaix/snapcast/releases/download/v0.25.0/snapserver_0.25.0-1_armhf.deb"

- name: modify snapserver sources
  lineinfile:
    path: "/etc/snapserver.conf"
    insertafter: "^# meta: meta:"
    line: "source = pipe:///tmp/snapfifoleft?name=Source-Library"
  notify: restart snapserver
  
- name: modify snapserver sources
  lineinfile:
    path: "/etc/snapserver.conf"
    insertafter: "^# meta: meta:"
    line: "source = pipe:///tmp/snapfiforight?name=Source-Radio"
  notify: restart snapserver

- name: modify snapserver sources
  lineinfile:
    path: "/etc/snapserver.conf"
    insertafter: "^# meta: meta:"
    line: "source = airplay:///shairport-sync?name=Source-Airplay"
  notify: restart snapserver 
